## NumPy Temelleri ve Array İşlemleri

In [5]:
import numpy as np     #numpy -> np olarak da import edilebilir

In [6]:
myList = [10,20,30,40]

In [7]:
type(myList)

list

In [9]:
np.array(myList)

array([10, 20, 30, 40])

In [10]:
my_numpy_array = np.array(myList)

In [11]:
type(my_numpy_array)

numpy.ndarray

In [12]:
#Array arithmetic

In [14]:
my_list1 = [1,2]

In [20]:
my_list2 = [2,3]

In [21]:
my_list1 + my_list2

[1, 2, 2, 3]

In [22]:
my_npmy_array1 = np.array(my_list1)

In [23]:
my_npmy_array2 = np.array(my_list2)

In [24]:
my_npmy_array1 + my_npmy_array2

array([3, 5])

In [25]:
my_npmy_array1 * my_npmy_array2

array([2, 6])

In [26]:
my_npmy_array1 - my_npmy_array2

array([-1, -1])

In [27]:
my_npmy_array1 / my_npmy_array2

array([0.5       , 0.66666667])

### Array Oluşturma ve İndeksleme

In [42]:
# arange & indexing

In [46]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
np_array = np.arange(0,10)

In [52]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np_array[-1]

np.int64(9)

In [60]:
np_array[0]

np.int64(0)

In [63]:
np_array[1:10:2]

array([1, 3, 5, 7, 9])

In [64]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [65]:
# random

#### not: "randn standart normal dağılımdan veri çekerken, randint belirttiğimiz aralıkta tam sayı üretir."

In [66]:
np.random.randn(4) 

array([ 0.63748247,  0.67627189, -0.70743803,  2.10372208])

In [67]:
np.random.randn(4,4) 

array([[-0.90691251,  0.88494612,  2.00373911,  0.08828376],
       [ 1.05047605,  1.7008175 , -0.97533012,  0.0431313 ],
       [ 1.30226729,  0.98096464, -1.13422458,  0.60779651],
       [ 0.23157046, -0.28399967, -1.05434999,  0.16646735]])

In [69]:
np.random.randint(1,300,5) # 1 ile 300 arasınnda rastgele 5 sayı veriyor.

array([ 70, 182,  37,  15, 243], dtype=int32)