### İki Boyutlu Arrayler (Matrisler) ve Lineer Cebir İşlemleri

In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [22]:
my_matrix[1]

[15, 20]

In [7]:
my_matrix[1][0]

15

In [23]:
my_matrix

[[5, 10], [15, 20]]

In [8]:
# row * column

In [17]:
numpy_matrix = np.array([[5,10],[15,20]])

In [19]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [26]:
numpy_matrix.sum()

np.int64(50)

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.random.random((4,4))

array([[0.44329394, 0.98290713, 0.77233643, 0.41593771],
       [0.82621859, 0.32394134, 0.16346606, 0.32290285],
       [0.8392841 , 0.37140585, 0.74439075, 0.75408132],
       [0.16342113, 0.49609456, 0.67506023, 0.19725122]])

In [37]:
# matrix arithmetic

In [38]:
first_array = np.array([[10,20],[30,40]])

In [39]:
second_array = np.array([[5,15],[25,35]])

In [40]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [41]:
first_array * 3

array([[ 30,  60],
       [ 90, 120]])

In [42]:
first_array  / 2

array([[ 5., 10.],
       [15., 20.]])

In [43]:
first_array + 5

array([[15, 25],
       [35, 45]])

In [67]:
third_array = np.array([[10],[20]])

In [65]:
third_array.shape

(2, 1)

In [60]:
first_array.shape

(2, 2)

In [61]:
third_array + first_array

array([[20, 30],
       [50, 60]])

In [68]:
# matrix multiplication

In [69]:
first_array

array([[10, 20],
       [30, 40]])

In [70]:
second_array

array([[ 5, 15],
       [25, 35]])

In [71]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

#### Dot Product (Matris Çarpımı) Kuralı :

1.matrisin sütun (column) sayısı ile 2. matrisin satır (row) sayısı EŞİT olmalıdır.

Sonuç matrisinin boyutu: (1. matrisin satır sayısı, 2. matrisin sütun sayısı) olur.

In [74]:
first_matrix = np.array([[10,20,30]])

In [76]:
first_matrix.shape

(1, 3)

In [78]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [79]:
second_matrix.shape

(3, 2)

In [81]:
# first_matrix * second_matrix  : Hata alırız Çarpma işlemi gerçekleşmez

In [83]:
result_matrix = first_matrix.dot(second_matrix)

In [84]:
result_matrix

array([[120, 180]])

In [86]:
result_matrix.shape

(1, 2)