In [1]:
import numpy as np

In [6]:
new_array = np.random.randint(1,100,20)

In [9]:
new_array

array([29, 27, 21, 56, 70, 28, 88, 87, 12, 53, 95, 25, 92, 87, 43, 16, 23,
       63, 93, 48], dtype=int32)

In [15]:
new_array > 25

array([ True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True])

#### Koşullu Seçim (Boolean Masking)

Array içindeki elemanları belirli bir koşula göre filtrelemek için kullanılır

In [14]:
new_array[new_array > 25]

array([29, 27, 56, 70, 28, 88, 87, 53, 95, 92, 87, 43, 63, 93, 48],
      dtype=int32)

#### Boyut ve Şekil Değiştirme (Reshape & Transpose)

In [16]:
# transpose & reshape

In [18]:
matrix_array = np.array ([[10,20],[20,30],[30,40]])

In [20]:
matrix_array.shape

(3, 2)

In [21]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [22]:
matrix_array.transpose()     # Rowların ve columların yerlerini değiştiriyor.

array([[10, 20, 30],
       [20, 30, 40]])

In [23]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [24]:
random_array = np.random.random((6,1))

In [25]:
random_array

array([[0.04479026],
       [0.25198338],
       [0.62525582],
       [0.58451521],
       [0.64561928],
       [0.00501693]])

In [26]:
random_array.shape

(6, 1)

In [27]:
random_array.reshape(2,3)

array([[0.04479026, 0.25198338, 0.62525582],
       [0.58451521, 0.64561928, 0.00501693]])

In [31]:
random_array.reshape(3,2)

array([[0.04479026, 0.25198338],
       [0.62525582, 0.58451521],
       [0.64561928, 0.00501693]])

In [32]:
veri_listesi = [1, 2, 3, 4, 5]
numpy_dizisi = np.array(veri_listesi)